language: ruby
bundler_args: --without debugger development mysql sqlite

rvm:
  - 1.9.3

env:
  - "DB=postgres"

before_script:
  - sh -c "cp config/database.$DB.yml config/database.yml"
  - sh -c "cp config/application.travis.yml config/application.yml"
  - sh -c "psql -c 'create database jobsworth_test;' -U postgres"

script:
  - "bundle exec rake ci:build"

# To stop Travis from running tests for a new commit,
# add the following to your commit message: [ci skip]
# You should add this when you edit documentation or comments, etc.
