# The settings in this file are very important. You can specify different environments
# such as 'staging' or 'test', however usually only 'production' is needed

development: &development
  domain: <%= domain %>  # The tenant specific hostname will be prepended to this domain
  productName: <%= company_name %>
  SSL: false
  store_root: <%%= Rails.root.join("store") %>

  # outbound email settings
  email_domain: <%= domain %>
  replyto: admin
  from: admin
  prefix: "[Jobsworth]"

  smtp:
    address: localhost
    port: 25
    domain: <%= domain %>

  # Exceptions in jobsworth might generate an error email. Who should we send it to?
  # You can find out more: https://github.com/smartinez87/exception_notification#installation
  exception_notifier:
    email:
      email_prefix: "[Jobsworth error] "
      sender_address: error@<%= domain %>
      exception_recipients: [exceptions@example.com]

  receiving_emails:
    secret: k4soAd4lqr4Znh_jL7EcaA       # this key protects the API for sending emails into jobsworth

  # Allow user and company creation?
  contact_creation_allowed: <%= contact_creation %>
  # Display the SCM changes
  use_scm_activities: true

  # Users can sign up/in via various oauth providers
  # omniauth:
  #   fluenta:
  #     app_id: 123
  #     secret: 456
  #     site:   http://oauth.site.com

  # Localeapp api key
  localeapp:
    api_key:
    sending_environments: []
    polling_environments: []
    reloading_environments: []

test:
  <<: *development

production:
  <<: *development
